# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_01.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(545, 436)
        MainWindow.setLocale(QtCore.QLocale(
            QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setLocale(QtCore.QLocale(
            QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_4.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setStyleSheet("background-color: rgb(0, 0, 0);\n"
                                   "color: rgb(255, 255, 255);\n"
                                   "font: 75 10pt \"MS Shell Dlg 2\";\n"
                                   "")
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.listView = QtWidgets.QListView(self.tab_2)
        self.listView.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.listView.setObjectName("listView")
        self.verticalLayout_2.addWidget(self.listView)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(-1, 22, -1, -1)
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setObjectName("label")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.toolButton = QtWidgets.QToolButton(self.tab_2)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout_2.addWidget(self.toolButton)
        self.formLayout.setLayout(
            1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(
            2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_3.setWhatsThis("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_3.addWidget(self.lineEdit_3)
        self.toolButton_2 = QtWidgets.QToolButton(self.tab_2)
        self.toolButton_2.setObjectName("toolButton_2")
        self.horizontalLayout_3.addWidget(self.toolButton_2)
        self.formLayout.setLayout(
            2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(
            3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.comboBox = QtWidgets.QComboBox(self.tab_2)
        self.comboBox.setToolTip("")
        self.comboBox.setEditable(False)
        self.comboBox.setCurrentText("")
        self.comboBox.setModelColumn(0)
        self.comboBox.setObjectName("comboBox")
        self.formLayout.setWidget(
            3, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.horizontalLayout_4.addLayout(self.formLayout)
        self.horizontalLayout_4.setStretch(0, 2)
        self.horizontalLayout_4.setStretch(1, 5)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_5.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_5.setSpacing(10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setStyleSheet("background-color: rgb(0, 0, 0);\n"
                                   "color: rgb(255, 255, 255);\n"
                                   "font: 75 10pt \"MS Shell Dlg 2\";\n"
                                   "")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.listView_2 = QtWidgets.QListView(self.tab)
        self.listView_2.setObjectName("listView_2")
        self.verticalLayout.addWidget(self.listView_2)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_PlayerStages = QtWidgets.QVBoxLayout()
        self.verticalLayout_PlayerStages.setContentsMargins(-1, 22, -1, 0)
        self.verticalLayout_PlayerStages.setSpacing(10)
        self.verticalLayout_PlayerStages.setObjectName(
            "verticalLayout_PlayerStages")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout_5 = QtWidgets.QFormLayout(self.groupBox_3)
        self.formLayout_5.setContentsMargins(9, 9, 9, 9)
        self.formLayout_5.setSpacing(6)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setObjectName("label_9")
        self.formLayout_5.setWidget(
            0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(1000)
        self.spinBox.setSingleStep(10)
        self.spinBox.setProperty("value", 20)
        self.spinBox.setObjectName("spinBox")
        self.formLayout_5.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.spinBox)
        self.verticalLayout_PlayerStages.addWidget(self.groupBox_3)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout_3.setContentsMargins(9, 9, 9, 9)
        self.formLayout_3.setSpacing(6)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.formLayout_3.setWidget(
            0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.spinBox_2 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_2.setMaximum(100)
        self.spinBox_2.setObjectName("spinBox_2")
        self.formLayout_3.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.spinBox_2)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.formLayout_3.setWidget(
            1, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.spinBox_3 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_3.setMaximum(100)
        self.spinBox_3.setProperty("value", 100)
        self.spinBox_3.setObjectName("spinBox_3")
        self.formLayout_3.setWidget(
            1, QtWidgets.QFormLayout.FieldRole, self.spinBox_3)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.formLayout_3.setWidget(
            3, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.spinBox_4 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_4.setMinimum(5)
        self.spinBox_4.setMaximum(30)
        self.spinBox_4.setProperty("value", 20)
        self.spinBox_4.setObjectName("spinBox_4")
        self.formLayout_3.setWidget(
            3, QtWidgets.QFormLayout.FieldRole, self.spinBox_4)
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setObjectName("label_13")
        self.formLayout_3.setWidget(
            4, QtWidgets.QFormLayout.FieldRole, self.label_13)
        self.verticalLayout_PlayerStages.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_4 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_4.setContentsMargins(9, 9, 9, 9)
        self.formLayout_4.setSpacing(6)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setObjectName("label_14")
        self.formLayout_4.setWidget(
            0, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox.setMinimum(70.0)
        self.doubleSpinBox.setMaximum(130.0)
        self.doubleSpinBox.setProperty("value", 100.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.formLayout_4.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox)
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setObjectName("label_15")
        self.formLayout_4.setWidget(
            1, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_2.setPrefix("")
        self.doubleSpinBox_2.setMinimum(70.0)
        self.doubleSpinBox_2.setMaximum(130.0)
        self.doubleSpinBox_2.setProperty("value", 100.0)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.formLayout_4.setWidget(
            1, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_2)
        self.verticalLayout_PlayerStages.addWidget(self.groupBox_2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_PlayerStages)
        self.horizontalLayout_5.setStretch(0, 2)
        self.horizontalLayout_5.setStretch(1, 5)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_7 = QtWidgets.QLabel(self.tab_3)
        self.label_7.setGeometry(QtCore.QRect(100, 150, 47, 14))
        self.label_7.setObjectName("label_7")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_6 = QtWidgets.QLabel(self.tab_4)
        self.label_6.setGeometry(QtCore.QRect(40, 30, 151, 16))
        self.label_6.setObjectName("label_6")
        self.checkBox = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox.setGeometry(QtCore.QRect(40, 80, 201, 18))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_2.setGeometry(QtCore.QRect(50, 110, 131, 18))
        self.checkBox_2.setObjectName("checkBox_2")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.textEdit = QtWidgets.QTextEdit(self.tab_5)
        self.textEdit.setGeometry(QtCore.QRect(20, 20, 461, 171))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.tabWidget.addTab(self.tab_5, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 545, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.statusbar.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.statusbar.setAutoFillBackground(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.comboBox.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Max Sick Gains"))
        self.tab_2.setWhatsThis(_translate(
            "MainWindow", "<html><head/><body><p>Fitness stages are the heart of this mod. They encompass body shape and muscle definition.</p><p>These stages can be assigned to both Player and NPCs at their respective pages.</p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "Fitness stages"))
        self.listView.setToolTip(_translate(
            "MainWindow", "Right click to add/delete Fitness stages"))
        self.listView.setStatusTip(_translate(
            "MainWindow", "List of all Fitness stages available"))
        self.listView.setWhatsThis(_translate(
            "MainWindow", "<html><head/><body><p>Use this list to navigate through all Fitness stages available.<br/>These Fitness stages can be used on Player and NPCs separately.</p><p>Right click to add/delete stages.</p></body></html>"))
        self.label.setText(_translate("MainWindow", "Name"))
        self.lineEdit.setStatusTip(_translate(
            "MainWindow", "This name will be displayed everytime you reach this Fitness stage"))
        self.lineEdit.setWhatsThis(_translate(
            "MainWindow", "<html><head/><body><p>Whenever you reach a new state (either by progressing or regressing) you will get a message saying:</p><p><pre>You fitness stage is: &lt;name&gt;</pre></p></body></html>"))
        self.lineEdit.setPlaceholderText(
            _translate("MainWindow", "Enter a name"))
        self.label_2.setText(_translate("MainWindow", "F. Bodyslide"))
        self.lineEdit_2.setStatusTip(_translate(
            "MainWindow", "Bodyslide preset applied to females who are at this Fitness stage"))
        self.lineEdit_2.setPlaceholderText(_translate(
            "MainWindow", "Select a Bodyslide preset"))
        self.toolButton.setText(_translate("MainWindow", "..."))
        self.label_3.setText(_translate("MainWindow", "M. Bodyslide"))
        self.lineEdit_3.setStatusTip(_translate(
            "MainWindow", "Bodyslide preset applied to females who are at this Fitness stage"))
        self.lineEdit_3.setPlaceholderText(
            _translate("MainWindow", "Not implemented yet"))
        self.toolButton_2.setText(_translate("MainWindow", "..."))
        self.label_5.setText(_translate("MainWindow", "Muscle definition"))
        self.comboBox.setStatusTip(_translate(
            "MainWindow", "Is this stage for fit, fat or plain bodies?"))
        self.comboBox.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>What kind of normal maps will be assigned to this Fitness stage? Fit, fat or plain?</p><p>This won\'t do anything unless you activate</p><p><span style=\" font-family:\'Courier New\';\">Muscle definition &gt; Use for player <br/></span>or <br/><span style=\" font-family:\'Courier New\';\">Muscle definition &gt; Use for NPCs</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(
            self.tab_2), _translate("MainWindow", "Fitness stages"))
        self.label_8.setText(_translate("MainWindow", "Fitness stages"))
        self.groupBox_3.setTitle(_translate(
            "MainWindow", "Stage configuration"))
        self.label_9.setText(_translate("MainWindow", "Min. days"))
        self.groupBox.setTitle(_translate("MainWindow", "Bodyslide preset"))
        self.label_10.setText(_translate("MainWindow", "Min. Weight"))
        self.spinBox_2.setWhatsThis(_translate(
            "MainWindow", "<html><head/><body><p>Imagine your Bodyslide preset looks like this</p><p><img src=\":/img/bs-default.png\"/></p><p>and you set this value to 20.</p><p>This means this preset will act as </p><p><img src=\":/img/bs-low_20.png\"/></p><p>for the player.</p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "Max. weight"))
        self.spinBox_3.setWhatsThis(_translate(
            "MainWindow", "<html><head/><body><p>Imagine your Bodyslide preset looks like this</p><p><img src=\":/img/bs-default.png\"/></p><p>and you set this value to 50.</p><p>This means this preset will act as </p><p><img src=\":/img/bs-high_50.png\"/></p><p>for the player.</p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "Blend at"))
        self.spinBox_4.setSuffix(_translate("MainWindow", "%"))
        self.label_13.setText(_translate("MainWindow", "Total days: 1000"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Head resizing"))
        self.label_14.setText(_translate("MainWindow", "Initial size"))
        self.doubleSpinBox.setSuffix(_translate("MainWindow", "%"))
        self.label_15.setText(_translate("MainWindow", "Final size"))
        self.doubleSpinBox_2.setSuffix(_translate("MainWindow", "%"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(
            self.tab), _translate("MainWindow", "Player stages"))
        self.label_7.setText(_translate("MainWindow", "One handed"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(
            self.tab_3), _translate("MainWindow", "Training"))
        self.label_6.setText(_translate(
            "MainWindow", "Exclude for these races"))
        self.checkBox.setText(_translate("MainWindow", "Activate for player"))
        self.checkBox_2.setText(_translate("MainWindow", "Activate for NPCs"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(
            self.tab_4), _translate("MainWindow", "Muscle definition"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                         "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                         "p, li { white-space: pre-wrap; }\n"
                                         "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.14286pt; font-weight:400; font-style:normal;\">\n"
                                         "<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8.14286pt; color:#aa0000;\">ERROR: </span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sed eleifend libero. Curabitur ut lobortis. </p>\n"
                                         "<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8.14286pt; color:#ffaa00;\">WARNING:</span><span style=\" font-size:8.14286pt;\"> Proin tempor ultrices elementum. Donec quis molestie nulla. Curabitur elit tellus, ornare et erat sed, eleifend tempus turpis. Nulla et. </span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(
            self.tab_5), _translate("MainWindow", "Export to game"))
# import res_rc
